version: 0.2

phases:
  install:
    commands:
      - echo "No installation needed for static HTML"

  pre_build:
    commands:
      - echo "Preparing build..."

  build:
    commands:
      - echo "Building static HTML site"
      - mkdir -p output
      # Copy all files to output directory
      - cp -r * output/ || true
      # Remove buildspec from artifacts
      - rm -f output/buildspec.yml

  post_build:
  commands:
    - aws cloudfront create-invalidation \
      --distribution-id REAL_DISTRIBUTION_ID \
      --paths "/*"

      
artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: no
